# -*- coding: utf-8 -*-
"""sistema_de_auditoria_de_recursos_corporativos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0vyV-V02ClWUBVaNH5moeHt5Wm_wYNi

## **Sistema de Auditoria de Recursos Corporativos**
> Maria Vitória Pereira Alves
"""

import time
#Iniciando com a biblioteca para calcular o tempo

# Auditor criado:
def auditor(func):
    def wrapper(*args, **kwargs):
        print("\n" + "-"*25 + "<3"*1 + "-"*25)
        print("SISTEMA DE AUDITORIA - RELATÓRIO DE EXECUÇÃO")
        print("-"*50)

        # Eu pego os nomes que passei para ignorar (estão no *args)
        excluidos = args[1:] if len(args) > 1 else "Nenhum"
        print(f"Departamentos escolhidos para pular: {excluidos}")
        print(f"Parâmetros de conversão definidos: {kwargs}")

        # Marcando o tempo de início para saber quanto tempo leva pra rodar
        tempo_inicial = time.time()

        # Executando a função principal e guardo o total e a lista detalhada
        valor_total, lista_detalhada = func(*args, **kwargs)

        # Marco o tempo final e calculo a diferença (final - o inicial)
        tempo_final = time.time()
        processamento = tempo_final - tempo_inicial

        # Percorro a lista para exibir cada valor que o programa identificou
        #(Fiz isso com o intuito de mostrar claramente todos os valores que foram encontrados dentro do dicionário e, também "esconder" o que excluimos)
        print("\nTodos os valores encontrados no sistema:")
        for item in lista_detalhada:
            print(f"-> {item}")

        print(f"\nTempo de processamento: {processamento:.6f} segundos")
        print("*"*25 + "<3"*1 + "*"*25)

        return valor_total
    return wrapper

# Aplicando o meu auditor aqui para ele rodar junto com o cálculo
@auditor
def calcular_orcamento(estrutura_dados, *args_excluir, **kwargs_ajuste):

    # Nessa lista vazia coloco todos os valores que encontrei para apresentar depois, conforme falei acima
    registros_individuais = []

    # Criei esta função interna para conseguir navegar em todos os níveis
    def navegar_estrutura(dicionario_atual):
        soma_acumulada = 0 #Defino um valor inicial zerado para ir incrementando

        # Aqui o programa olha para cada chave e cada valor
        for chave, valor in dicionario_atual.items():
            # Verifica se o nome atual está na lista de exclusão
            if chave in args_excluir:
                continue

            # Se encontrar outro dicionário, entra nele (recursão)
            if isinstance(valor, dict): #isinstance utilizei para conseguir verificar os tipos de dados antes de tratar no codigo
                resultado_recursivo = navegar_estrutura(valor)
                soma_acumulada = soma_acumulada + resultado_recursivo

            #Quando o programa encontrar um numero, ele junta com tudoe soma no total final
            elif isinstance(valor, (int, float)):
                registros_individuais.append(f"{chave}: {valor:,.2f}")
                soma_acumulada = soma_acumulada + valor

        return soma_acumulada

    # Inicio o processo de navegação pelos dados que recebi
    valor_base = navegar_estrutura(estrutura_dados)

    # Pego de volta a taxa de câmbio que passei no kwargs
    taxa = kwargs_ajuste.get('taxa_cambio', 1.0)

    # O programa final calcula o valor final multiplicando pela taxa (solicitada no exercicio)
    valor_convertido = valor_base * taxa

    return valor_convertido, registros_individuais #retorna o valor convertido (já com a taxa) e os registros individuais, que solicitei o detalhamento para apresentar

# Montei o dicionário com a estrutura da empresa, focada em logistica (inspirado na área que trabalho atualmente)
empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000,
                "Dados": 100000
            },
            "Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "RH": {
            "Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            },
            "Dp": {
                "Folhas de pagamento": 50000,
                "Rescisões": 100000
            }
        },
        "Financeiro": 40000,
        "Operacional": {
            "Caminhões": 1500000,
            "Fretes": 500000,
            "isenção de avarias": 300000
        }
    }
}

# Chamo a minha função principal passando os dados e as configurações, para funcionar certinho
resultado_final = calcular_orcamento(
    empresa_data,
    "Operacional",
    "Financeiro",
    taxa_cambio=5.20
)

print(f"VALOR TOTAL AUDITADO: R$ {resultado_final:,.2f}")